import pandas as pd

df = pd.read_excel("C:\\Users\\prasa\\Downloads\\logistics.xlsx",sheet_name="Logistics_Data") # Reads an Excel file from the specified path and sheet name into a DataFrame
# print(df.isnull().any(axis=0)) # Checks for null values in each row of


# count_null_values=df.isnull().sum() # Counts the number of null values in each column of the DataFrame
# print(count_null_values)

# null_cols=df.columns[df.isnull().any()] # Retrieves the column names that contain null values in the DataFrame
# print(null_cols)


# print(df.isnull().any(axis=1)) # Checks for null values in each row of the DataFrame and returns a boolean Series indicating which rows contain null values

# print(df.isnull()) # Checks for null values in the DataFrame and returns a DataFrame of the same shape with boolean values indicating which values are null


# Data={
#     'name':["prasanna", "praveen", "prashanth", None],
#     'age':[25, 30, 35, 40],
# }
# df1=pd.DataFrame(Data)
# print(df1)


# Replacing_null_value=df.fillna(0,inplace=True) # Replaces null values in the DataFrame with a specified value (in this case, 0) and modifies the original DataFrame
# print(df)



# print(df.isnull().sum()) # Counts the number of null values in each column of the DataFrame after replacing null values with 0

# Exporting_sheet=df.to_excel("C:\\Users\\prasa\\Downloads\\logistics_updated.xlsx", index=False) # Exports the DataFrame to an Excel file at the specified path without including the index in the output file
# print(Exporting_sheet,"Successfully exported to Excel")


# finding_duplicates=df.duplicated() # Checks for duplicate rows in the DataFrame and returns a boolean Series indicating which rows are duplicates
# get_only_duplicates=df[df.duplicated()] # Retrieves only the duplicate rows from the DataFrame based on the boolean Series generated by the duplicated() method
# print(get_only_duplicates)


# checking_perticular_column_in_duplicates=df.duplicated(subset=['Order_Date']) # Checks for duplicate rows in the DataFrame based on a specific column (replace 'column_name' with the actual column name) and returns a boolean Series indicating which rows are duplicates based on that column
# print(df[checking_perticular_column_in_duplicates])



# Replace duplicate AWB values with empty cells, keep first occurrence

df1=pd.DataFrame({
    'score':['20', '30', '40', '20', '50']
})
print(df1.dtypes)

df1['score']=df1['score'].astype('int') # Converts the 'score' column in the DataFrame to integer data type
print(df1,df1.dtypes)

